/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package distantshoresmedia.org.model;

import java.util.ArrayList;

import distantshoresmedia.org.model.*;

public class Character extends BaseDataClass {


	private int unicodeCharacterID;
 	public void setUnicodeCharacterID(int unicodeCharacterID) {
		this.unicodeCharacterID = unicodeCharacterID;
	}
	public int getUnicodeCharacterID() {
		return unicodeCharacterID;
	}


	private String modMask;
 	public void setModMask(String modMask) {
		this.modMask = modMask;
	}
	public String getModMask() {
		return modMask;
	}


	private int sortNumber;
 	public void setSortNumber(int sortNumber) {
		this.sortNumber = sortNumber;
	}
	public int getSortNumber() {
		return sortNumber;
	}


	private int keyPositionID;
 	public void setKeyPositionID(int keyPositionID) {
		this.keyPositionID = keyPositionID;
	}
	public int getKeyPositionID() {
		return keyPositionID;
	}

    public ArrayList<UnicodeCharacter> unicodeCharacters = new ArrayList<UnicodeCharacter>();
    public void setUnicodeCharacters(ArrayList<UnicodeCharacter> characters){
        this.unicodeCharacters = unicodeCharacters;
    }
    public ArrayList<UnicodeCharacter> getUnicodeCharacters(){
        return this.unicodeCharacters;
    }

    public Character(int uid, int created, int updated, int unicodeCharacterID, String modMask, int sortNumber, int keyPositionID){
        super(uid, created, updated);
        this.unicodeCharacterID = unicodeCharacterID;
        this.modMask = modMask;
        this.sortNumber = sortNumber;
        this.keyPositionID = keyPositionID;
    }
}