/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.distantshoresmedia.model;

import org.distantshoresmedia.model.*;

public class KeyboardType extends BaseDataClass {


	private String osVariant;
 	public void setOsVariant(String osVariant) {
		this.osVariant = osVariant;
	}
	public String getOsVariant() {
		return osVariant;
	}


	private String name;
 	public void setName(String name) {
		this.name = name;
	}
	public String getName() {
		return name;
	}


	private String os;
 	public void setOs(String os) {
		this.os = os;
	}
	public String getOs() {
		return os;
	}


    public KeyboardType(int uid, int created, int updated, String osVariant, String name, String os){
        super(uid, created, updated);
        this.osVariant = osVariant;
        this.name = name;
        this.os = os;
    }
}