/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package distantshoresmedia.org.model;

import distantshoresmedia.org.model.*;

public class UnicodeCharacter extends BaseDataClass {


	private String utf8Hex;
 	public void setUtf8Hex(String utf8Hex) {
		this.utf8Hex = utf8Hex;
	}
	public String getUtf8Hex() {
		return utf8Hex;
	}


	private String englishDesc;
 	public void setEnglishDesc(String englishDesc) {
		this.englishDesc = englishDesc;
	}
	public String getEnglishDesc() {
		return englishDesc;
	}

    public UnicodeCharacter(int uid, int created, int updated, String utf8Hex, String englishDesc){
        super(uid, created, updated);
        this.utf8Hex = utf8Hex;
        this.englishDesc = englishDesc;
    }
}