/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.distantshoresmedia.model;


import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.Arrays;

public class BaseKeyboard {

    static final private String kUIDKey = "keyboard_id";
    static final private String kKeyboardNameKey = "keyboard_name";
    static final private String kCreatedKey = "created_at";
    static final private String kUpdatedKey = "updated_at";
    static final private String kIsoRegionKey = "iso_region";
    static final private String kIsoLanguageKey = "iso_language";
    static final private String kKeybaordVariantKey = "keyboard_variants";


    private Integer keyboardId;
    public void setKeyboardId(Integer keyboardId) {
        this.keyboardId = keyboardId;
    }
    public Integer getKeyboardId() {
        return keyboardId;
    }

    private String keyboardName;
    public void setKeyboardName(String keyboardName) {
        this.keyboardName = keyboardName;
    }
    public String getKeyboardName() {
        return keyboardName;
    }

    private String createdAt;
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }
    public String getCreatedAt() {
        return createdAt;
    }

    private String updatedAt;
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getUpdatedAt() {
        return updatedAt;
    }

    private String isoRegion;
    public void setIsoRegion(String isoRegion) {
        this.isoRegion = isoRegion;
    }
    public String getIsoRegion() {
        return isoRegion;
    }

	private String isoLanguage;
 	public void setIsoLanguage(String isoLanguage) {
		this.isoLanguage = isoLanguage;
	}
	public String getIsoLanguage() {
		return isoLanguage;
	}

	private KeyboardVariant[] keyboardVariants;
 	public void setKeyboardVariants(KeyboardVariant[] keyboardVariants) {
		this.keyboardVariants = keyboardVariants;
	}
	public KeyboardVariant[] getKeyboardVariants() {
		return keyboardVariants;
	}


    public BaseKeyboard(Integer id, String name, String created, String updated, String isoRegion, String isoLanguage, KeyboardVariant[] variants){
        this.keyboardId = id;
        this.keyboardName = name;
        this.createdAt = created;
        this.updatedAt = updated;
        this.isoRegion = isoRegion;
        this.isoLanguage = isoLanguage;
        this.keyboardVariants = variants;
    }


    static public BaseKeyboard getKeyboardFromJsonObject(JSONObject jsonObj){

        System.out.println("Got to BaseKeyboard");
        try {
            int id = jsonObj.getInt(kUIDKey);
            String name = jsonObj.getString(kKeyboardNameKey);
            String created = jsonObj.getString(kCreatedKey);
            String updated = jsonObj.getString(kUpdatedKey);
            String isoRegion = jsonObj.getString(kIsoRegionKey);
            String isoLanguage = jsonObj.getString(kIsoLanguageKey);

            JSONArray rows = jsonObj.getJSONArray(kKeybaordVariantKey);
            KeyboardVariant[] variants = new KeyboardVariant[rows.length()];

            for(int i = 0; i < rows.length(); i++) {
                JSONObject rowObj = rows.getJSONObject(i);

                variants[i] = KeyboardVariant.getKeyboardFromJsonObject(rowObj);
            }

            BaseKeyboard keyboard = new BaseKeyboard(id, name, created, updated, isoRegion, isoLanguage, variants);

            return  keyboard;
        }

        catch (JSONException e) {
            System.out.println("BaseKeyboard JSONException: " + e.toString());
            return null;
        }
    }

    @Override
    public String toString() {
        return "BaseKeyboard{" +
                "keyboardId=" + keyboardId +
                ", keyboardName='" + keyboardName + '\'' +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                ", isoRegion='" + isoRegion + '\'' +
                ", isoLanguage='" + isoLanguage + '\'' +
                ", keyboardVariants=" + Arrays.toString(keyboardVariants) +
                '}';
    }
}