/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.distantshoresmedia.model;


import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.Arrays;

import de.greenrobot.dao.DaoException;

public class BaseKeyboard {

    static final private String kUIDKey = "keyboard_id";
    static final private String kKeyboardNameKey = "keyboard_name";
    static final private String kCreatedKey = "created_at";
    static final private String kUpdatedKey = "updated_at";
    static final private String kIsoRegionKey = "iso_region";
    static final private String kIsoLanguageKey = "iso_language";
    static final private String kKeybaordVariantKey = "keyboard_variants";

    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient BaseKeyboardDao myDao;

    private long id;
    public void setId(Integer id) {
        this.id = id;
    }
    public long getId() {
        return id;
    }

    private String Name;
    public void setName(String name) {
        this.Name = name;
    }
    public String getName() {
        return Name;
    }

    private String createdAt;
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }
    public String getCreatedAt() {
        return createdAt;
    }

    private String updatedAt;
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getUpdatedAt() {
        return updatedAt;
    }

    private String isoRegion;
    public void setIsoRegion(String isoRegion) {
        this.isoRegion = isoRegion;
    }
    public String getIsoRegion() {
        return isoRegion;
    }

	private String isoLanguage;
 	public void setIsoLanguage(String isoLanguage) {
		this.isoLanguage = isoLanguage;
	}
	public String getIsoLanguage() {
		return isoLanguage;
	}

	private KeyboardVariant[] keyboardVariants;
 	public void setKeyboardVariants(KeyboardVariant[] keyboardVariants) {
		this.keyboardVariants = keyboardVariants;
	}
	public KeyboardVariant[] getKeyboardVariants() {
		return keyboardVariants;
	}


    public BaseKeyboard(long id, String name, String created, String updated, String isoRegion, String isoLanguage, KeyboardVariant[] variants){
        this.id = id;
        this.Name = name;
        this.createdAt = created;
        this.updatedAt = updated;
        this.isoRegion = isoRegion;
        this.isoLanguage = isoLanguage;
        this.keyboardVariants = variants;
    }


    static public BaseKeyboard getKeyboardFromJsonObject(JSONObject jsonObj){

        System.out.println("Got to BaseKeyboard");
        try {
            int id = jsonObj.getInt(kUIDKey);
            String name = jsonObj.getString(kKeyboardNameKey);
            String created = jsonObj.getString(kCreatedKey);
            String updated = jsonObj.getString(kUpdatedKey);
            String isoRegion = jsonObj.getString(kIsoRegionKey);
            String isoLanguage = jsonObj.getString(kIsoLanguageKey);

            JSONArray rows = jsonObj.getJSONArray(kKeybaordVariantKey);
            KeyboardVariant[] variants = new KeyboardVariant[rows.length()];

            for(int i = 0; i < rows.length(); i++) {
                JSONObject rowObj = rows.getJSONObject(i);

                variants[i] = KeyboardVariant.getKeyboardFromJsonObject(rowObj);
            }

            BaseKeyboard keyboard = new BaseKeyboard(id, name, created, updated, isoRegion, isoLanguage, variants);

            return  keyboard;
        }

        catch (JSONException e) {
            System.out.println("BaseKeyboard JSONException: " + e.toString());
            return null;
        }
    }

    @Override
    public String toString() {
        return "BaseKeyboard{" +
                "Id=" + id +
                ", Name='" + Name + '\'' +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                ", isoRegion='" + isoRegion + '\'' +
                ", isoLanguage='" + isoLanguage + '\'' +
                ", keyboardVariants=" + Arrays.toString(keyboardVariants) +
                '}';
    }


    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getBaseKeyboardDao() : null;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetVariants() {
//        KeyboardVariant = null;
    }

    /** Convenient call for {@link (Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /** Convenient call for {@link(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /** Convenient call for {@link(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }
}