package org.distantshoresmedia.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.distantshoresmedia.model.BaseKeyboard;
import org.distantshoresmedia.model.KeyboardVariant;
import org.distantshoresmedia.model.KeyPosition;
import org.distantshoresmedia.model.KeyCharacter;


import org.distantshoresmedia.model.BaseKeyboardDao;
import org.distantshoresmedia.model.KeyboardVariantDao;
import org.distantshoresmedia.model.KeyPositionDao;
import org.distantshoresmedia.model.KeyCharacterDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT....I mean it was...but it isn't now

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig baseKeybaordDaoConfig;
    private final DaoConfig keyboardVariantDaoConfig;
    private final DaoConfig keyPostionDaoConfig;
    private final DaoConfig keyCharacterDaoConfig;


    private final BaseKeyboardDao baseKeyboardDao;
    private final KeyboardVariantDao keyboardVariantDao;
    private final KeyPositionDao keyPositionDao;
    private final KeyCharacterDao keyCharacterDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);
		
		

        baseKeybaordDaoConfig = daoConfigMap.get(BaseKeyboardDao.class).clone();
        baseKeybaordDaoConfig.initIdentityScope(type);

        keyboardVariantDaoConfig = daoConfigMap.get(KeyboardVariantDao.class).clone();
        keyboardVariantDaoConfig.initIdentityScope(type);

        keyPostionDaoConfig = daoConfigMap.get(KeyPositionDao.class).clone();
        keyPostionDaoConfig.initIdentityScope(type);
		
        keyCharacterDaoConfig = daoConfigMap.get(KeyCharacterDao.class).clone();
        keyCharacterDaoConfig.initIdentityScope(type);

        baseKeyboardDao = new BaseKeyboardDao(baseKeybaordDaoConfig, this);
        keyboardVariantDao = new KeyboardVariantDao(keyboardVariantDaoConfig, this);
        keyPositionDao = new KeyPositionDao(keyPostionDaoConfig, this);
		keyCharacterDao = new KeyCharacterDao(keyCharacterDaoConfig, this);

        registerDao(BaseKeyboard.class, baseKeyboardDao);
        registerDao(KeyboardVariant.class, keyboardVariantDao);
        registerDao(KeyPosition.class, keyPositionDao);
		registerDao(KeyCharacter.class, keyCharacterDao);
    }
    
    public void clear() {
        baseKeybaordDaoConfig.getIdentityScope().clear();
//        keyboardVariantDao.getIdentityScope().clear();
//        keyPositionDao.getIdentityScope().clear();
//		keyCharacterDao.getIdentityScope().clear();
    }

    public BaseKeyboardDao getBaseKeyboardDao() {
        return baseKeyboardDao;
    }

    public KeyboardVariantDao getKeyboardVariantDao() {
        return keyboardVariantDao;
    }

    public KeyPositionDao getKeyPositionDao() {
        return keyPositionDao;
    }
	
    public KeyCharacterDao getKeyCharacterDao() {
        return keyCharacterDao;
    }
	
	

}
