/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.distantshoresmedia.model;

public class KeyboardVariant {
	private java.lang.String created_at;

 	public void setCreated_at(java.lang.String created_at) {
		this.created_at = created_at;
	}

	public java.lang.String getCreated_at() {
		return created_at;
	}

	private java.lang.String name;

 	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

	private KeyCharacter[][] keys;

 	public void setKeys(KeyCharacter[][] keys) {
		this.keys = keys;
	}

	public KeyCharacter[][] getKeys() {
		return this.keys;
	}

	private java.lang.String updated_at;

 	public void setUpdated_at(java.lang.String updated_at) {
		this.updated_at = updated_at;
	}

	public java.lang.String getUpdated_at() {
		return updated_at;
	}

}