/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.distantshoresmedia.model;

public class KeyPosition {
	private KeyCharacter[] characters;

 	public void setCharacters(KeyCharacter[] characters) {
		this.characters = characters;
	}

	public KeyCharacter[] getCharacters() {
		return characters;
	}

	private java.lang.Integer percent_width;

 	public void setPercent_width(java.lang.Integer percent_width) {
		this.percent_width = percent_width;
	}

	public java.lang.Integer getPercent_width() {
		return percent_width;
	}

}