/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.distantshoresmedia.model;

import android.util.JsonReader;
import android.util.JsonWriter;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.Arrays;

public class KeyPosition {

    static final private String kPercentWidthKey = "percent_width";
    static final private String kRowIndexKey = "row_index";
    static final private String kCollumnIndexKey= "column_index";
    static final private String kCharactersKey = "characters";

    private double percentWidth;
    public void setPercentWidth(double percentWidth) {
        this.percentWidth = percentWidth;
    }
    public double getPercentWidth() {
        return percentWidth;
    }

	private KeyCharacter[] characters;
 	public void setCharacters(KeyCharacter[] characters) {
		this.characters = characters;
	}
	public KeyCharacter[] getCharacters() {
		return characters;
	}

    private int row;
    public int getRow() {
        return row;
    }
    public void setRow(int row) {
        this.row = row;
    }

    private int column;
    public void setColumn(int columns) {
        this.column = column;
    }
    public int getColumn() {
        return column;
    }

    public KeyPosition(double percentWidth, KeyCharacter[] characters, int row, int column){
        this.percentWidth = percentWidth;
        this.characters = characters;
        this.row = row;
        this.column = column;
    }


    static public KeyPosition getKeyboardFromJsonObject(JSONObject jsonObj){

        System.out.println("Got to KeyPosition");

        try {
            double width = jsonObj.getDouble(kPercentWidthKey);
            int column = jsonObj.getInt(kRowIndexKey);
            int row = jsonObj.getInt(kCollumnIndexKey);

            JSONArray jsonChars = jsonObj.getJSONArray(kCharactersKey);

            KeyCharacter[] characters = new KeyCharacter[jsonChars.length()];

            for(int i = 0; i < jsonChars.length(); i++){

                JSONObject character = jsonChars.getJSONObject(i);
                characters[i] = KeyCharacter.getCharacterFromJsonObject(character);
            }

            KeyPosition position = new KeyPosition(width, characters, row, column);
            return position;
        }

        catch (JSONException e) {
            System.out.println("KeyPosition JSONException: " + e.toString());
            return null;
        }
    }

    @Override
    public String toString() {
        return "KeyPosition{" +
                "percentWidth=" + percentWidth +
                ", characters=" + Arrays.toString(characters) +
                ", row=" + row +
                ", column=" + column +
                '}';
    }
}