package org.distantshoresmedia.model.daoModels;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import org.distantshoresmedia.model.daoModels.BaseKeyboard;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BASE_KEYBOARD.
*/
public class BaseKeyboardDao extends AbstractDao<BaseKeyboard, Long> {

    public static final String TABLENAME = "BASE_KEYBOARD";

    /**
     * Properties of entity BaseKeyboard.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property KeyboardName = new Property(1, String.class, "keyboardName", false, "KEYBOARD_NAME");
        public final static Property IsoRegion = new Property(2, String.class, "isoRegion", false, "ISO_REGION");
        public final static Property IsoLanguage = new Property(3, String.class, "isoLanguage", false, "ISO_LANGUAGE");
        public final static Property CreatedAt = new Property(4, java.util.Date.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(5, java.util.Date.class, "updatedAt", false, "UPDATED_AT");
        public final static Property AvailableKeyboardId = new Property(6, long.class, "availableKeyboardId", false, "AVAILABLE_KEYBOARD_ID");
    };

    private DaoSession daoSession;

    private Query<BaseKeyboard> availableKeyboard_BaseKeyboardsQuery;

    public BaseKeyboardDao(DaoConfig config) {
        super(config);
    }
    
    public BaseKeyboardDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BASE_KEYBOARD' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'KEYBOARD_NAME' TEXT," + // 1: keyboardName
                "'ISO_REGION' TEXT," + // 2: isoRegion
                "'ISO_LANGUAGE' TEXT," + // 3: isoLanguage
                "'CREATED_AT' INTEGER," + // 4: createdAt
                "'UPDATED_AT' INTEGER," + // 5: updatedAt
                "'AVAILABLE_KEYBOARD_ID' INTEGER NOT NULL );"); // 6: availableKeyboardId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BASE_KEYBOARD'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BaseKeyboard entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String keyboardName = entity.getKeyboardName();
        if (keyboardName != null) {
            stmt.bindString(2, keyboardName);
        }
 
        String isoRegion = entity.getIsoRegion();
        if (isoRegion != null) {
            stmt.bindString(3, isoRegion);
        }
 
        String isoLanguage = entity.getIsoLanguage();
        if (isoLanguage != null) {
            stmt.bindString(4, isoLanguage);
        }
 
        java.util.Date createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(5, createdAt.getTime());
        }
 
        java.util.Date updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindLong(6, updatedAt.getTime());
        }
        stmt.bindLong(7, entity.getAvailableKeyboardId());
    }

    @Override
    protected void attachEntity(BaseKeyboard entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BaseKeyboard readEntity(Cursor cursor, int offset) {
        BaseKeyboard entity = new BaseKeyboard( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // keyboardName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // isoRegion
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // isoLanguage
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // createdAt
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // updatedAt
            cursor.getLong(offset + 6) // availableKeyboardId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BaseKeyboard entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKeyboardName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIsoRegion(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIsoLanguage(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCreatedAt(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setUpdatedAt(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setAvailableKeyboardId(cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(BaseKeyboard entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(BaseKeyboard entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "baseKeyboards" to-many relationship of AvailableKeyboard. */
    public List<BaseKeyboard> _queryAvailableKeyboard_BaseKeyboards(long availableKeyboardId) {
        synchronized (this) {
            if (availableKeyboard_BaseKeyboardsQuery == null) {
                QueryBuilder<BaseKeyboard> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AvailableKeyboardId.eq(null));
                availableKeyboard_BaseKeyboardsQuery = queryBuilder.build();
            }
        }
        Query<BaseKeyboard> query = availableKeyboard_BaseKeyboardsQuery.forCurrentThread();
        query.setParameter(0, availableKeyboardId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAvailableKeyboardDao().getAllColumns());
            builder.append(" FROM BASE_KEYBOARD T");
            builder.append(" LEFT JOIN AVAILABLE_KEYBOARD T0 ON T.'AVAILABLE_KEYBOARD_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected BaseKeyboard loadCurrentDeep(Cursor cursor, boolean lock) {
        BaseKeyboard entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        AvailableKeyboard availableKeyboard = loadCurrentOther(daoSession.getAvailableKeyboardDao(), cursor, offset);
         if(availableKeyboard != null) {
            entity.setAvailableKeyboard(availableKeyboard);
        }

        return entity;    
    }

    public BaseKeyboard loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<BaseKeyboard> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<BaseKeyboard> list = new ArrayList<BaseKeyboard>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<BaseKeyboard> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<BaseKeyboard> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
