package org.distantshoresmedia.model.daoModels;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import org.distantshoresmedia.model.daoModels.AvailableKeyboardDao;
import org.distantshoresmedia.model.daoModels.BaseKeyboardDao;
import org.distantshoresmedia.model.daoModels.KeyboardVariantDao;
import org.distantshoresmedia.model.daoModels.KeyPositionDao;
import org.distantshoresmedia.model.daoModels.KeyCharacterDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 100): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 100;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        AvailableKeyboardDao.createTable(db, ifNotExists);
        BaseKeyboardDao.createTable(db, ifNotExists);
        KeyboardVariantDao.createTable(db, ifNotExists);
        KeyPositionDao.createTable(db, ifNotExists);
        KeyCharacterDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        AvailableKeyboardDao.dropTable(db, ifExists);
        BaseKeyboardDao.dropTable(db, ifExists);
        KeyboardVariantDao.dropTable(db, ifExists);
        KeyPositionDao.dropTable(db, ifExists);
        KeyCharacterDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(AvailableKeyboardDao.class);
        registerDaoClass(BaseKeyboardDao.class);
        registerDaoClass(KeyboardVariantDao.class);
        registerDaoClass(KeyPositionDao.class);
        registerDaoClass(KeyCharacterDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
