package org.distantshoresmedia.model.daoModels;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import org.distantshoresmedia.model.daoModels.KeyboardVariant;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table KEYBOARD_VARIANT.
*/
public class KeyboardVariantDao extends AbstractDao<KeyboardVariant, Long> {

    public static final String TABLENAME = "KEYBOARD_VARIANT";

    /**
     * Properties of entity KeyboardVariant.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property CreatedAt = new Property(2, java.util.Date.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(3, java.util.Date.class, "updatedAt", false, "UPDATED_AT");
        public final static Property BaseKeyboardId = new Property(4, long.class, "baseKeyboardId", false, "BASE_KEYBOARD_ID");
    };

    private DaoSession daoSession;

    private Query<KeyboardVariant> baseKeyboard_KeyboardVariantsQuery;

    public KeyboardVariantDao(DaoConfig config) {
        super(config);
    }
    
    public KeyboardVariantDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'KEYBOARD_VARIANT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NAME' TEXT," + // 1: name
                "'CREATED_AT' INTEGER," + // 2: createdAt
                "'UPDATED_AT' INTEGER," + // 3: updatedAt
                "'BASE_KEYBOARD_ID' INTEGER NOT NULL );"); // 4: baseKeyboardId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'KEYBOARD_VARIANT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, KeyboardVariant entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        java.util.Date createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(3, createdAt.getTime());
        }
 
        java.util.Date updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindLong(4, updatedAt.getTime());
        }
        stmt.bindLong(5, entity.getBaseKeyboardId());
    }

    @Override
    protected void attachEntity(KeyboardVariant entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public KeyboardVariant readEntity(Cursor cursor, int offset) {
        KeyboardVariant entity = new KeyboardVariant( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // createdAt
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // updatedAt
            cursor.getLong(offset + 4) // baseKeyboardId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, KeyboardVariant entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCreatedAt(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setUpdatedAt(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setBaseKeyboardId(cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(KeyboardVariant entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(KeyboardVariant entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "keyboardVariants" to-many relationship of BaseKeyboard. */
    public List<KeyboardVariant> _queryBaseKeyboard_KeyboardVariants(long baseKeyboardId) {
        synchronized (this) {
            if (baseKeyboard_KeyboardVariantsQuery == null) {
                QueryBuilder<KeyboardVariant> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.BaseKeyboardId.eq(null));
                baseKeyboard_KeyboardVariantsQuery = queryBuilder.build();
            }
        }
        Query<KeyboardVariant> query = baseKeyboard_KeyboardVariantsQuery.forCurrentThread();
        query.setParameter(0, baseKeyboardId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBaseKeyboardDao().getAllColumns());
            builder.append(" FROM KEYBOARD_VARIANT T");
            builder.append(" LEFT JOIN BASE_KEYBOARD T0 ON T.'BASE_KEYBOARD_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected KeyboardVariant loadCurrentDeep(Cursor cursor, boolean lock) {
        KeyboardVariant entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BaseKeyboard baseKeyboard = loadCurrentOther(daoSession.getBaseKeyboardDao(), cursor, offset);
         if(baseKeyboard != null) {
            entity.setBaseKeyboard(baseKeyboard);
        }

        return entity;    
    }

    public KeyboardVariant loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<KeyboardVariant> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<KeyboardVariant> list = new ArrayList<KeyboardVariant>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<KeyboardVariant> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<KeyboardVariant> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
