package org.distantshoresmedia.model.daoModels;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import org.distantshoresmedia.model.daoModels.KeyPosition;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table KEY_POSITION.
*/
public class KeyPositionDao extends AbstractDao<KeyPosition, Long> {

    public static final String TABLENAME = "KEY_POSITION";

    /**
     * Properties of entity KeyPosition.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PercentWidth = new Property(1, Integer.class, "percentWidth", false, "PERCENT_WIDTH");
        public final static Property Row = new Property(2, Integer.class, "row", false, "ROW");
        public final static Property Column = new Property(3, Integer.class, "column", false, "COLUMN");
        public final static Property KeyboardVariantId = new Property(4, long.class, "keyboardVariantId", false, "KEYBOARD_VARIANT_ID");
    };

    private DaoSession daoSession;

    private Query<KeyPosition> keyboardVariant_KeyPositionsQuery;

    public KeyPositionDao(DaoConfig config) {
        super(config);
    }
    
    public KeyPositionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'KEY_POSITION' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'PERCENT_WIDTH' INTEGER," + // 1: percentWidth
                "'ROW' INTEGER," + // 2: row
                "'COLUMN' INTEGER," + // 3: column
                "'KEYBOARD_VARIANT_ID' INTEGER NOT NULL );"); // 4: keyboardVariantId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'KEY_POSITION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, KeyPosition entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer percentWidth = entity.getPercentWidth();
        if (percentWidth != null) {
            stmt.bindLong(2, percentWidth);
        }
 
        Integer row = entity.getRow();
        if (row != null) {
            stmt.bindLong(3, row);
        }
 
        Integer column = entity.getColumn();
        if (column != null) {
            stmt.bindLong(4, column);
        }
        stmt.bindLong(5, entity.getKeyboardVariantId());
    }

    @Override
    protected void attachEntity(KeyPosition entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public KeyPosition readEntity(Cursor cursor, int offset) {
        KeyPosition entity = new KeyPosition( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // percentWidth
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // row
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // column
            cursor.getLong(offset + 4) // keyboardVariantId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, KeyPosition entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPercentWidth(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setRow(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setColumn(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setKeyboardVariantId(cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(KeyPosition entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(KeyPosition entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "keyPositions" to-many relationship of KeyboardVariant. */
    public List<KeyPosition> _queryKeyboardVariant_KeyPositions(long keyboardVariantId) {
        synchronized (this) {
            if (keyboardVariant_KeyPositionsQuery == null) {
                QueryBuilder<KeyPosition> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.KeyboardVariantId.eq(null));
                keyboardVariant_KeyPositionsQuery = queryBuilder.build();
            }
        }
        Query<KeyPosition> query = keyboardVariant_KeyPositionsQuery.forCurrentThread();
        query.setParameter(0, keyboardVariantId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getKeyboardVariantDao().getAllColumns());
            builder.append(" FROM KEY_POSITION T");
            builder.append(" LEFT JOIN KEYBOARD_VARIANT T0 ON T.'KEYBOARD_VARIANT_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected KeyPosition loadCurrentDeep(Cursor cursor, boolean lock) {
        KeyPosition entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        KeyboardVariant keyboardVariant = loadCurrentOther(daoSession.getKeyboardVariantDao(), cursor, offset);
         if(keyboardVariant != null) {
            entity.setKeyboardVariant(keyboardVariant);
        }

        return entity;    
    }

    public KeyPosition loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<KeyPosition> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<KeyPosition> list = new ArrayList<KeyPosition>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<KeyPosition> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<KeyPosition> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
