/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.distantshoresmedia.model;

import org.distantshoresmedia.model.*;

public class KeyboardVariant extends BaseDataClass {


	private String name;
 	public void setName(String name) {
		this.name = name;
	}
	public String getName() {
		return name;
	}


	private int keyboardID;
 	public void setKeyboardID(int keyboardID) {
		this.keyboardID = keyboardID;
	}
	public int getKeyboardID() {
		return keyboardID;
	}


	private int keyboardTypeID;
 	public void setKeyboardTypeID(int keyboardTypeID) {
		this.keyboardTypeID = keyboardTypeID;
	}
	public int getKeyboardTypeID() {
		return keyboardTypeID;
	}

    public KeyboardVariant(int uid, int created, int updated, int keyboardID, String name, int keyboardTypeID){
        super(uid, created, updated);
        this.keyboardID = keyboardID;
        this.name = name;
        this.keyboardTypeID = keyboardTypeID;
    }
}